spring.datasource.url=jdbc:mysql://localhost:3306/bookdb
spring.datasource.username=rootdev
spring.datasource.password=NewPassword123!dev
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true